
services:
  wan-multi-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount checkpoint directory - update this path to your local checkpoint directory
      - ${CHECKPOINT_DIR:-./cache}:/app/cache
      # Optional: Mount a directory for saving generated videos
      - ${OUTPUT_DIR:-./output}:/app/output
      # Mount specific model directory if provided
      - ${MODEL_DIR:-./models}:/app/models
    ports:
      - "7860:7860"  # Gradio web interface
    environment:
      # Set to the number of GPUs you want to use
      - NUM_GPUS=${NUM_GPUS:-2}
      # Set to the parallelism strategy: "fsdp" or "sequence"
      - PARALLEL_STRATEGY=${PARALLEL_STRATEGY:-fsdp}
      # Set ulysses_size and ring_size for sequence parallelism
      - ULYSSES_SIZE=${ULYSSES_SIZE:-2}
      - RING_SIZE=${RING_SIZE:-1}
      # Set to the port for the Gradio server
      - SERVER_PORT=${SERVER_PORT:-7860}
    # Use runtime: nvidia to enable GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${NUM_GPUS:-2}
              capabilities: [gpu]
